@startuml
'https://plantuml.com/class-diagram

package controleur{

    abstract Controleur implements Observateur{
        Controleur()
        setModel(Model model)
    }

    interface Observateur{
        void reagir()
    }

    class ControleurInformationConsultation{
    }

    class ControleurGlobal extends Controleur{
    }

    class CollectionSatellite{
    }

    class ControleurDetail extends Controleur{
        int posSatellite
    }

    class ControleurMenu extends Controleur{
    }

    class ControleurInformation extends Controleur{
    }

    class ControleurListeTags extends Controleur{
        int posSatellite
    }

    class ControleurRechercheTags extends Controleur{
    }
}

CollectionSatellite "1"--left Controleur
ControleurDetail "1"-right-"*" ControleurInformation
ControleurInformation --"1" Information
ControleurInformationConsultation --"1" Information


@enduml