@startuml
'https://plantuml.com/component-diagram

[Scene] -- [BorderPane]

[BorderPane] --"gauche" [MenuBar]
[MenuBar] --"*" [Menu]
[Menu] -- [MenuItem]

[BorderPane] --"centre" [ScrollPane]
[ScrollPane] -- [GridPane]
[GridPane] --"*" [VBox]
[VBox] -- [ImageView]
[VBox] -- [Label]

[BorderPane] --"bas" [HBox]
[HBox] -- [Button]
[HBox] -- [MenuButton]
[MenuButton] --"*" [MenuItm]

@enduml