@startuml
'https://plantuml.com/class-diagram

interface Iterable #aliceblue;line:blue;line.dotted;text:blue


package model{

    class Model extends SujetObserve{
        Model()
        void ajouter()
    }

    class GestionnaireObjets implements Iterable{
        gestionnaireObjets()
        void ajouter()
        void trierApparition()
        void trierDate()
        void trierNom()
    }

    class Satellite{
        String nom
        String identifiant
        Satellite(String nom)
    }

    class SujetObserve{
        void notifierObservateurs()
        void ajouterObservateur(Observateur... obs)
    }

    interface Observateur{
        void reagir()
    }

    class FabriqueIdentifiants<<(S,#FF7788)>>{
       int identifiant
       String getIdentifiant()
       void reset()
    }

    class Information {
        String titre
        ArrayList<String> texte
        void setTitre(String titre)
        void setTexte(String texte)
        String getTitre()
        String getTexte()
    }

    class MotsClef {
        String valeur
    }

}

FabriqueIdentifiants --"1" FabriqueIdentifiants
SujetObserve -right-"*" Observateur
Model -left-"1" GestionnaireObjets
GestionnaireObjets --"*" Satellite
Satellite --"*" Information
Satellite --"*" MotsClef


@enduml