@startuml
'https://plantuml.com/class-diagram

class CollectionSatellites extends SujetObserve{
    CollectionSatellites()
}
class Satellite{
    String nom
    String identifiant
    Satellite(String nom)
}
class SujetObserve{
    void notifierObservateurs()
    void ajouterObservateur()
}
interface Observateur{
    void reagir()
}

SujetObserve --"*" Observateur
CollectionSatellites --"*" Satellite


@enduml