@startuml
'https://plantuml.com/class-diagram

package controleur{
    abstract Controleur implements Observateur{
        Controleur()
        setModel(Model model)
    }

    interface Observateur{
        void reagir()
    }

    class PanneauGlobale extends Controleur{
        void vueDetail(String identifiant)
    }

    class Model
    class PanneauDetail extends Controleur{
        void ajouterInformation(PanneauInformations info)
    }

    class PanneauInformation extends Controleur{
        String titre
        String texte
        void modifierTitre(String newTitre)
        void modifierTexte(String newTexte)
        String getTitre()
        String getTexte
    }

    class PanneauMenu extends Controleur{
        void quitter()
        void sauvegarder()
        void importerDonnee(String dossier)
        void recherche(String valeur)
    }

    class PanneauOutils extends Controleur{
        void vueGlobale()
        void sauvegarder()
        void changerDonnee()
    }

    class PanneauBottom extends Controleur{
        void panneauGauche()
        void panneauDroite()
    }
}


Model "1"--left Controleur
PanneauDetail -right-"*" PanneauInformation
PanneauDetail --"1" Satellite
PanneauInformation --"1" Information

@enduml