@startuml
'https://plantuml.com/component-diagram

[Scene] -- [BorderPane]
[BorderPane] --"gauche" [MenuBar]
[MenuBar] -- "2" [Menu]
[Menu] -- [MenuItem]
[BorderPane] --"haut" [ImageView]
[BorderPane] --"bas 2" [Button]
[BorderPane] --"centre" [ScrollPane]
[ScrollPane] -- [VBox]
[HBox] -- [Label]


@enduml